---
replicas: 1
deploymentStrategy: RollingUpdate

image:
  repository: mvisonneau/gitlab-ci-pipelines-exporter
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  annotations: {}
  labels: {}

resources: {}
#  limits:
#    cpu: 50m
#    memory: 64Mi
#  requests:
#    cpu: 50m
#    memory: 64Mi

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
#
nodeSelector: {}

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Set the security context of the pods
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context
##
securityContext:
  runAsUser: 65534  # run as nobody user instead of root

## Actual configuration of the exporter
##
config: {}
  # gitlab:
  #   url: https://gitlab.example.com
  #   token: xrN14n9-ywvAFxxxxxx
  # polling_interval_seconds: 30
  # projects:
  #   - name: foo/project
  #     refs: [master]
  #   - name: bar/project
  #     refs: [dev,master]
  # wildcards:
  #   - owner:
  #       name: foo
  #       kind: group
  #     refs: [master]
  #     search: 'bar' # optional
